---
downloads: ~/.ansible-downloads/

configure_osx: true

homebrew_installed_packages:
  # - ansible # installed via pip
  - git
  - gpg
  - mas
  - node
  - nvm
  - pyenv

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - firefox
  - google-chrome

mas_installed_apps: []
mas_email: "{{ apple_id_user }}"
mas_password: "{{ apple_id_password }}"

