---

- name: Run piper home linux server setup
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: print out the hostname of target
      command: hostname
    - name: add google linux key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present 
    - name: Add UKUU repository 
      apt_repository:
        repo: ppa:teejee2008/ppa
    - name: Install UKUU
      apt:
        name: ukuu
        state: present
        update_cache: yes
    - name: Upgrade Firefox
      apt:
        name: firefox
        state: present
    - name: Install vim
      apt:
        name: vim
        state: present
    - name: Install lm sensors
      apt:
        name: lm-sensors
        state: present
    - name: Install ffmpeg
      apt:
        name: ffmpeg
        state: present
    - name: install spotify cli
      pip:
        name: spotify-cli-linux
        executable: pip3
    - name: install nmap
      apt:
        name: nmap
        state: present
    - name: docker key add
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add docker stable
      apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
    - name: install docker
      apt: name={{ item }} state=installed
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: create docker group
      group:
        name: docker
        state: present
# TODO: modify this to be an exec command that adds the user, we
# don't want to override all existing users for wisosim, just add on top
#    - name: add wisosim user to docker group
#      user:
#        name: wisosim
#        state: present
#        groups: docker
    - name: install tmux
      apt:
        name: tmux
        state: present

