---

- name: Run piper home linux server setup
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: print out the hostname of target
      command: hostname
    - name: Add UKUU repository 
      apt_repository:
        repo: ppa:teejee2008/ppa
    - name: Install UKUU
      apt:
        name: ukuu
        state: present
        update_cache: yes
    - name: Upgrade Firefox
      apt:
        name: firefox
        state: present
    - name: Install vim
      apt:
        name: vim
        state: present
    - name: Install lm sensors
      apt:
        name: lm-sensors
        state: present
    - name: Install ffmpeg
      apt:
        name: ffmpeg
        state: present

