---
- name: Check if AWS CLI is installed.
  shell: which aws
  register: aws_install_status
- when: aws_install_status.rc == 1
  block:
    - name: Download AWS CLI installer
      get_url:
        url: https://awscli.amazonaws.com/AWSCLIV2.pkg
        dest: AWSCLIV2.pkg

