---
- name: create neovim config directory
  file:
    path: ~/.config/nvim
    state: directory

- name: create nvm config directory
  file:
    path: ~/.nvm
    state: directory

- name: create ssh directory
  file:
    path: ~/.ssh
    state: directory

